[package]
name = "crosswind"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
if-addrs = "0.10.1"
socket2 = "0.4.7"
thiserror = "1.0.38"
tokio = { version = "1.26.0", features = ["full"] }
